apiVersion: apps/v1
kind: Deployment
metadata:
  name: facturation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facturation-service
  template:
    metadata:
      labels:
        app: facturation-service
    spec:
      containers:
        - name: facturation-service
          image: ayhouri/facturation-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service.default.svc.cluster.local:9999
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---
---
apiVersion: v1
kind: Service
metadata:
  name: facturation-service
spec:
  selector:
    app: facturation-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer