apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - name: security-service
          image: ayhouri/security-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9999
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service.default.svc.cluster.local:9999
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  selector:
    app: security-service
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: LoadBalancer