# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reservation.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'reservation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11reservation.proto\"0\n\x16ReservationByIdRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\x03\"\xb1\x01\n\x13ReservationResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06userId\x18\x02 \x01(\x03\x12\x11\n\tchambreId\x18\x03 \x01(\x03\x12\x12\n\ndate_debut\x18\x04 \x01(\t\x12\x10\n\x08\x64\x61te_fin\x18\x05 \x01(\t\x12\x15\n\rmontant_total\x18\x06 \x01(\x02\x12\x13\n\x04user\x18\x07 \x01(\x0b\x32\x05.User\x12\x19\n\x07\x63hambre\x18\x08 \x01(\x0b\x32\x08.Chambre\"q\n\x04User\x12\x0b\n\x03nom\x18\x01 \x01(\t\x12\x0e\n\x06prenom\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x11\n\ttelephone\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64resse\x18\x05 \x01(\t\x12\x0c\n\x04role\x18\x06 \x01(\t\x12\x0b\n\x03\x63ni\x18\x07 \x01(\t\"t\n\x07\x43hambre\x12\x0e\n\x06numero\x18\x01 \x01(\t\x12\x13\n\x0bnombre_lits\x18\x02 \x01(\x03\x12\x0c\n\x04prix\x18\x03 \x01(\x02\x12\r\n\x05image\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x12\n\ndisponible\x18\x06 \x01(\x08\x32Y\n\x12ReservationService\x12\x43\n\x12GetReservationById\x12\x17.ReservationByIdRequest\x1a\x14.ReservationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reservation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVATIONBYIDREQUEST']._serialized_start=21
  _globals['_RESERVATIONBYIDREQUEST']._serialized_end=69
  _globals['_RESERVATIONRESPONSE']._serialized_start=72
  _globals['_RESERVATIONRESPONSE']._serialized_end=249
  _globals['_USER']._serialized_start=251
  _globals['_USER']._serialized_end=364
  _globals['_CHAMBRE']._serialized_start=366
  _globals['_CHAMBRE']._serialized_end=482
  _globals['_RESERVATIONSERVICE']._serialized_start=484
  _globals['_RESERVATIONSERVICE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
